version: '3.9'

services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    restart: always
    networks:
      - internal_network

  prestashop:
    container_name: prestashop
    build:
      context: .
      dockerfile: ./.docker/prestashop/Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - 8000:80
      - 8001:443
    networks:
      - internal_network

networks:
  internal_network:
