ersion: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop

  prestashop:  
    container_name: prestashop
    depends_on:
      - mysql
    image: heyimjustalex/presta_img_local:presta_img_local_v1
    ports:
      - 17608:80
      - 17609:443  
    restart: always
    environment:
      DB_SERVER: mysql
      DB_USER: root
      DB_PASSWD: root
      DB_NAME: prestashop
      PS_FOLDER_ADMIN: admin
      PS_FOLDER_INSTALL: install
      PS_INSTALL_AUTO: 0  
    networks:
      - prestashop

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - prestashop

networks:
  prestashop: