version: '3.9'

services:
  web:
    container_name: web
    build:
      context: ./web
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html/

  db:
    container_name: mysql8
    build:
      context: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lamps
    ports:
      - 3306:3306

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  # db:
  #    image: postgres
  #    restart: always
  #    environment:
  #      POSTGRES_USER: root
  #      POSTGRES_PASSWORD: root
  #      POSTGRES_DB: test