<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMtm97qg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMtm97qg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMtm97qg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMtm97qg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMtm97qg\appProdProjectContainer([
    'container.build_hash' => 'Mtm97qg',
    'container.build_id' => '17d412c4',
    'container.build_time' => 1635868534,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMtm97qg');
