<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNrazwft\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNrazwft/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNrazwft.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNrazwft\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNrazwft\appProdProjectContainer([
    'container.build_hash' => 'Nrazwft',
    'container.build_id' => 'd4242e02',
    'container.build_time' => 1634738977,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNrazwft');
