<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2v0smd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2v0smd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerX2v0smd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerX2v0smd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerX2v0smd\appProdProjectContainer([
    'container.build_hash' => 'X2v0smd',
    'container.build_id' => 'c2ad32fb',
    'container.build_time' => 1635868535,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2v0smd');
